### ISSUE TITLE
[BUG] Неактуальность расписания

### ISSUE THREAD

**Issue by IvLaptev** [Ninja-Official/rtu-mirea-schedule-api#27]
**Описание ошибки**
Время от времени сервис раздаёт устаревшее расписание. Несколько студентов жаловались, на отсутствие преподавателей, но оказывалось, что приложение показывало не ту аудиторию, что скачанное только что расписание. Случилось это где-то в начале недели.

**Дополнительный текст**
Вероятнее всего проблема в расписании кронтаба. Если уж обновлять расписание раз в день, то делать это стоит ближе к началу учебного дня часов в 7-8, но не в полночь. \
Как ещё более надёжный вариант можно дёргать ручку с `/refresh`, например, раз в 4 часа. При этом необязательно каждый раз парсить  расписание. После скачивания расписания можно сравнить `last-modified` из заголовков ответа с соответствующим заголовком последнего распаршенного расписания. Таким образом получится, что кронтаб будет работать чаще, а парсер наоборот только тогда, когда в расписании действительно появились изменения. \
Как бонус: будут известны точные дата и время обновления расписания на сайте.

**Comment by 0niel** [comment]
Спасибо! Реализовано в #30
